### POST USER / SIGNUP
POST  http://localhost:3000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "username":"amaliaz",
    "email":"amalia@gmail.com",
    "password":"123"
}


### SIGNIN USER 
POST http://localhost:3000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email" : "amaliaz",
    "password" : "123"
}


### UPDATE USER 
POST  http://localhost:3000/api/auth/user-update HTTP/1.1
Content-Type: application/json

{
    "id":"clhiub2c00004smw0oa21cq33",
    "name":"amalia",
    "email":"ar@gmail.com",
    "password":"1234",
    "active":true,
    "masterUserRoleId":2
}



### POST ASET PARTAI
POST http://localhost:3000/api/aset-partai/aset-partai-post HTTP/1.1
Content-Type: application/json

{
    "name":"Aset pertama",
    "serialNumber":"fj93ur893hi38hfjji",
    "pengguna":"AAA",
    "penanggungJawab":"BBB",
    "harga":60000,
    "tglPembelian":"2023-04-10 00:00:00",
    "lokasiPembelian":"Denpasar",
    "garansi":"gafaranfdkslf",
    "masterStatusAsetId": 1,
    "keterangan":"Penambahan aset",
    "masterKategoriAsetId":2,
    "deskripsi":"Percobaan",
    "img":"gambar1.jpg"
}


### UPDATE ASET PARTAI
POST http://localhost:3000/api/aset-partai/aset-partai-update HTTP/1.1
Content-Type: application/json

{
    "id" :"clhiubniw0007smw0oilb9qro",
    "name":"Aset kedua",
    "serialNumber":"fdsfjldk",
    "pengguna":"BBBB",
    "penanggungJawab":"AAAAa",
    "harga":65000,
    "tglPembelian":"2023-04-09 00:00:00",
    "lokasiPembelian":"Tabanan",
    "garansi":"garansinya",
    "masterStatusAsetId": 2,
    "keterangan":"Penambahann aset",
    "masterKategoriAsetId":3,
    "deskripsi":"Percobaan Aset",
    "img":"gambar3.jpg"
}


### GET ONE ASET PARTAI 
GET http://localhost:3000/api/aset-partai/aset-partai-get-one?id=clhiubniw0007smw0oilb9qro HTTP/1.1



### POST DATA DIRI 
POST http://localhost:3000/api/form-data-diri/data-diri-post HTTP/1.1
Content-Type: application/json

{
    "nik" : "51710349000230",
    "name":"Amalia",
    "tempatLahir" : "Blitar",
    "tanggalLahir" : "1999-12-07 00:00:00",
    "phoneNumber" : "0884564854",
    "alamat" : "Didalam rumah",
    "rtRw" : "3/2",
    "userId" : "clhiub2c00004smw0oa21cq33",
    "masterJenisKelaminId" : 2,
    "masterAgamaId" : 1,
    "masterPekerjaanId" : 2,
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterKecamatanId" : 1,
    "masterDesaId" : 1
}


### UPDATE DATA DIRI
POST http://localhost:3000/api/form-data-diri/data-diri-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clhiukkku0009smw0ubsm8wjd",
    "name" : "Amalia Dwi",
    "nik" : "51710349000230",
    "tempatLahir" : "Denpasar",
    "tanggalLahir" : "1999-11-07 00:00:00",
    "phoneNumber" : "0884564800",
    "alamat" : "Didalam gedung",
    "rtRw" : "2/2",
    "userId" : "clhiub2c00004smw0oa21cq33",
    "masterJenisKelaminId" : 1,
    "masterAgamaId" : 1,
    "masterPekerjaanId" : 2,
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterKecamatanId" : 1,
    "masterDesaId" : 1
}

### GET ONE DATA DIRI
GET http://localhost:3000/api/form-data-diri/data-diri-get-one?id=clhiub2c00004smw0oa21cq33 HTTP/1.1



### POST ANGGOTA AFILIATIF
POST http://localhost:3000/api/anggota-afiliatif/anggota-afiliatif-post HTTP/1.1
Content-Type: application/json

{
    "userId":"clhiub2c00004smw0oa21cq33",
    "masterOrganisasiAfiliatifId" : 1
}


### UPDATE ANGGOTA AFILIATIF
POST http://localhost:3000/api/anggota-afiliatif/anggota-afiliatif-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clhiumvpi000bsmw06hbbinjk",
    "userId" : "clhiub2c00004smw0oa21cq33",
    "masterOrganisasiAfiliatifId" : 2
}

### POST USER MEDIA SOSIAL
POST http://localhost:3000/api/auth/user-media-sosial/user-media-sosial-post HTTP/1.1
Content-Type: application/json

{
    "name" : "@username1",
    "link" : "link ig",
    "userId" : "clhiub2c00004smw0oa21cq33",
    "masterMediaSocialId" : 2
}

### UPDATE USER MEDIA SOSIAL
POST http://localhost:3000/api/auth/user-media-sosial/user-media-sosial-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clhiup2ho000fsmw0h0vh1ilw",
    "link" : "link link",
    "name" : "yup yup",
    "userId" : "clhiub2c00004smw0oa21cq33",
    "masterMediaSocialId" :2
}


### POST TPS DPT
POST http://localhost:3000/api/peta-kekuatan/tps-dpt/tps-dpt-post HTTP/1.1
Content-Type: application/json

{
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterKecamatanId" : 1,
    "masterDesaId" : 1,
    "masterNomorUrutTPSId" : 1,
    "dptLakilaki" : 30,
    "dptPerempuan" : 20
}

### UPDATE TPS DPT 
POST http://localhost:3000/api/peta-kekuatan/tps-dpt/tps-dpt-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clhiupwt2000hsmw0cik3zk7i",
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterKecamatanId" : 1,
    "masterDesaId" : 1,
    "masterNomorUrutTPSId" : 1,
    "dptLakilaki" : 30,
    "dptPerempuan" : 20
}

### POST CALON PEMILIH POTENSIAL
POST http://localhost:3000/api/peta-kekuatan/cpt/cpt-post HTTP/1.1
Content-Type: application/json

{
    "masterCalonPemilihPotensialId" : 1,
    "masterAgamaId" : 1,
    "masterPekerjaanId" : 1,
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterKecamatanId" : 1,
    "masterDesaId" : 1,
    "masterNomorUrutTPSId" : 1,
    "masterJenisKelaminId" : 1,
    "nik" : "12345123456",
    "nama" : "Amalia Dwi",
    "email" : "amaliadwi@gmail.com",
    "tanggalLahir" : "1999-12-07",
    "phoneNumber" : "0898978678",
    "alamat" : "Panjer",
    "statusSosial" : "Kaya"
}

### UPDATE CALON PEMILIH POTENSIAL
POST http://localhost:3000/api/peta-kekuatan/cpt/cpt-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clhiuqvf5000jsmw0ouhhhcyp",
    "masterCalonPemilihPotensialId" : 1,
    "masterAgamaId" : 1,
    "masterPekerjaanId" : 1,
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterKecamatanId" : 1,
    "masterDesaId" : 1,
    "masterNomorUrutTPSId" : 1,
    "masterJenisKelaminId" : 2,
    "nik" : "4568893487",
    "nama" : "Amalia Dwi",
    "email" : "amalia@gmail.com",
    "tanggalLahir" : "2000-12-07",
    "phoneNumber" : "0898978678",
    "alamat" : "Panjer",
    "statusSosial" : "Kaya"
}

### GET ONE CALON PEMILIH POTENSIAL
GET http://localhost:3000/api/peta-kekuatan/cpt/cpt-get-one?id=clhiuqvf5000jsmw0ouhhhcyp HTTP/1.1

### POST RENCANA KUNJUNGAN PRABOWO 
POST  http://localhost:3000/api/aksi-nyata/rencana-kunjungan-prabowo/rencana-kunjungan-prabowo-post HTTP/1.1
Content-Type: application/json

{
    "judul" : "Rencana pertama",
    "tanggal" : "2000-12-09",
    "img" : "gambar 1",
    "masterStatusAksiNyataId" : 1
}


### UPDATE RENCANA KUNJUNGAN PRABOWO
POST http://localhost:3000/api/aksi-nyata/rencana-kunjungan-prabowo/rencana-kunjungan-prabowo-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clhiuroil000lsmw00b2u1j93",
    "judul" : "Rencana pertama",
    "tanggal" : "2000-12-09",
    "img" : "gambar 1",
    "masterStatusAksiNyataId" : 2
}

### GET ONE RENCANA KUNJUNGAN PRABOWO 
GET http://localhost:3000/api/aksi-nyata/rencana-kunjungan-prabowo/rencana-kunjungan-prabowo-get-one?id=clhiuroil000lsmw00b2u1j93 HTTP/1.1

### POST RENCANA KUNJUNGAN GERINDRA
POST http://localhost:3000/api/aksi-nyata/rencana-kunjungan-gerindra/rencana-kunjungan-gerindra-post HTTP/1.1
Content-Type: application/json

{
    "judul" : "Rencana acara pertama",
    "tanggal" : "2000-12-23",
    "img" : "gambar",
    "masterStatusAksiNyataId" : 2
}


### UPDATE RENCANA KUNJUNGAN GERINDRA
POST http://localhost:3000/api/aksi-nyata/rencana-kunjungan-gerindra/rencana-kunjungan-gerindra-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clhiusrq1000nsmw0flhwb0fo",
    "judul" : "rencana kedua",
    "tanggal":"2000-12-25",
    "img" : "gambar 2",
    "masterStatusAksiNyataId" : 1
}

### GET ONE RENCANA KUNJUNGAN GERINDRA
GET http://localhost:3000/api/aksi-nyata/rencana-kunjungan-gerindra/rencana-kunjungan-gerindra-get-one?id=clhiusrq1000nsmw0flhwb0fo HTTP/1.1


### POST LIST UNDANGAN PRABOWO
POST http://localhost:3000/api/aksi-nyata/list-undangan-prabowo/list-undangan-prabowo-post HTTP/1.1
Content-Type: application/json

{
    "rencanaKunjunganPrabowoId" : "clhiuroil000lsmw00b2u1j93",
    "nama" : "Amalia"
}

### UPDATE LIST UNDANGAN PRABOWO
POST http://localhost:3000/api/aksi-nyata/list-undangan-prabowo/list-undangan-prabowo-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clhiuukbi000vsmw0pz79uavy",
    "rencanaKunjunganPrabowoId" : "clhiuroil000lsmw00b2u1j93",
    "nama" : "Dwi"
}

### GET ONE LIST UNDANGAN PRABOWO
GET http://localhost:3000/api/aksi-nyata/list-undangan-prabowo/list-undangan-prabowo-get-one?id=clhiuukbi000vsmw0pz79uavy HTTP/1.1

### POST LIST UNDANGAN GERINDRA
POST http://localhost:3000/api/aksi-nyata/list-undangan-gerindra/list-undangan-gerindra-post HTTP/1.1
Content-Type: application/json

{
    "rencanaKunjunganGerindraId" : "clhiusrq1000nsmw0flhwb0fo", 
    "nama" : "Ketua yayasan"
}

### UPDATE LIST UNDANGAN GERINDRA
POST http://localhost:3000/api/aksi-nyata/list-undangan-gerindra/list-undangan-gerindra-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clhiuwbs3000xsmw0sylvmr8e",
    "rencanaKunjunganGerindraId" : "clhiusrq1000nsmw0flhwb0fo",
    "nama" : "wakil ketua yayasan"
}

### GET ONE LIST UNDANGAN GERINDRA
GET http://localhost:3000/api/aksi-nyata/list-undangan-gerindra/list-undangan-gerindra-get-one?id=clgg5rnch000tacojru0y5759 HTTP/1.1


### GET ALL LIST UNDANGAN GERINDRA
GET http://localhost:3000/api/aksi-nyata/list-undangan-gerindra/list-undangan-gerindra-get-all HTTP/1.1


### POST EKSEKUTIF
POST http://localhost:3000/api/peta-kekuatan/eksekutif/eksekutif-post HTTP/1.1
Content-Type: application/json

{
    "userId" : "clhiub2c00004smw0oa21cq33",
    "masterProvinceId" : 1,
    "masterKabKotId" : null,
    "masterTingkatEksekutifId" : null,
    "masterJabatanEksekutifProvinsiId" : 1,
    "masterJabatanEksekutifKabKotId" : null,
    "masterJabatanEksekutifKabupatenId" : null,
    "masterJabatanEksekutifKotaId" : null,
    "masterStatusEksekutifId" : null,
    "namaLembaga" : "Wakil",
    "periode" : "2019",
    "alamatKantor" : "Jalan Pegangsaan Timur"
}

### UPDATE EKSEKUTIF
POST http://localhost:3000/api/peta-kekuatan/eksekutif/eksekutif-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clgg6z68b000vacojpc6wo1tb",
    "userId" : "clgg1bp040000acyjqn2nvilc",
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterTingkatEksekutifId" : 2,
    "masterJabatanEksekutifProvinsiId" : 1,
    "masterJabatanEksekutifKabKotId" : 1,
    "masterJabatanEksekutifKabupatenId" : 1,
    "masterJabatanEksekutifKotaId" : 1,
    "masterStatusEksekutifId" : 1,
    "namaLembaga" : "Wakil",
    "periode" : "2019",
    "alamatKantor" : "Jalan Pegangsaan Barat"
}


### GET ONE EKSEKUTIF
GET http://localhost:3000/api/peta-kekuatan/eksekutif/eksekutif-get-one?id=clgg6z68b000vacojpc6wo1tb HTTP/1.1



### POST LEGISLATIF
POST http://localhost:3000/api/peta-kekuatan/legislatif/legislatif-post HTTP/1.1
Content-Type: application/json

{
    "userId" : "clgg1bp040000acyjqn2nvilc",
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterTingkatLegislatifId" : 1,
    "jabatan" : "Ketua",
    "periode" : "2019",
    "noUrut" : 1,
    "dapil" : "Bali",
    "cakupanWilayah" : "Nasional",
    "akd" : "asdf"
}


### UPDATE LEGISLATIF
POST http://localhost:3000/api/peta-kekuatan/legislatif/legislatif-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clgg7u2y5000xacoj0cjcchsw",
    "userId" : "clgg1bp040000acyjqn2nvilc",
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterTingkatLegislatifId" : 1,
    "jabatan" : "WAKIL",
    "periode" : "2019",
    "noUrut" : 2,
    "dapil" : "Bali",
    "cakupanWilayah" : "Nasional",
    "akd" : "asdf"
}

### GET ONE LEGISLATIF
GET http://localhost:3000/api/peta-kekuatan/legislatif/legislatif-get-one?id=clgg7u2y5000xacoj0cjcchsw HTTP/1.1



### POST PARTAI PENGUSUNG EKSEKUTIF
POST http://localhost:3000/api/peta-kekuatan/partai-pengusung-eksekutif/partai-pengusung-eksekutif-post HTTP/1.1
Content-Type: application/json

{
    "eksekutifId" : "clgg6z68b000vacojpc6wo1tb",
    "masterPartaiPengusungId" : 1
}


### UPDATE PARTAI PENGUSUNG EKSEKUTIF
POST http://localhost:3000/api/peta-kekuatan/partai-pengusung-eksekutif/partai-pengusung-eksekutif-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clgg8a2mp000zacojoeesyv2y",
    "eksekutifId" : "clgg6z68b000vacojpc6wo1tb",
    "masterPartaiPengusungId" : 2
}



### POST DPD DPC MEDIA SOSIAL 
POST http://localhost:3000/api/sumber-daya-partai/dpd-dpc-media-social/dpd-dpc-media-social-post HTTP/1.1
Content-Type: application/json

{
    "masterMediaSocialId" : 2,
    "sumberDayaPartaiId" : "clgg9oijk0017acoj2t8ort8m",
    "name" : "username insert",
    "link" : "link sosmednyaaa"
}


### UPDATE DPD DPC MEDIA SOSIAL 
POST http://localhost:3000/api/sumber-daya-partai/dpd-dpc-media-social/dpd-dpc-media-social-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clgg9qb860019acojl95lm5if",
    "masterMediaSocialId" : 3,
    "sumberDayaPartaiId" : "clgg9oijk0017acoj2t8ort8m",
    "name" : "username update",
    "link" : "link sosmednya "
}



### POST SUMBER DAYA PARTAI / KEANGGOTAAN
POST http://localhost:3000/api/sumber-daya-partai/sumber-daya-partai-post HTTP/1.1
Content-Type: application/json

{
    "userId" : "clgg1bp040000acyjqn2nvilc",
    "masterStatusKeanggotaanId" : 1,
    "masterTingkatPengurusId" : 1,
    "masterJabatanId" : 1,
    "masterJabatanDewanPembinaId" : 1,
    "masterJabatanDewanPimpinanPusatId" : 1,
    "masterJabatanDewanPimpinanDaerahId" : 1,
    "masterJabatanDewanPimpinanCabangId" : 1,
    "masterJabatanPimpinanAnakCabangId" : 1,
    "masterJabatanPimpinanRantingId" : 1,
    "masterJabatanPerwakilanPartaiDiLuarNegeriId" : 1,
    "masterSayapPartaiId" : 1,
    "masterKaderPartaiId" : 1,
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterKecamatanId" : 1,
    "masterDesaId" : 1,
    "masterNegaraId" : 1,
    "alamatKantor" : "Panjer",
    "waAdmin" : "0984937483927"
}

### UPDATE SUMBER DAYA PARTAI / KEANGGOTAAN
POST http://localhost:3000/api/sumber-daya-partai/sumber-daya-partai-update HTTP/1.1
Content-Type: application/json

{
    "id" : "clgg9oijk0017acoj2t8ort8m",
    "userId" : "clgg1bp040000acyjqn2nvilc",
    "masterStatusKeanggotaanId" : 1,
    "masterTingkatPengurusId" : 1,
    "masterJabatanId" : 1,
    "masterJabatanDewanPembinaId" : 1,
    "masterJabatanDewanPimpinanPusatId" : 1,
    "masterJabatanDewanPimpinanDaerahId" : 1,
    "masterJabatanDewanPimpinanCabangId" : 1,
    "masterJabatanPimpinanAnakCabangId" : 1,
    "masterJabatanPimpinanRantingId" : 1,
    "masterJabatanPerwakilanPartaiDiLuarNegeriId" : 1,
    "masterSayapPartaiId" : 1,
    "masterKaderPartaiId" : 1,
    "masterProvinceId" : 1,
    "masterKabKotId" : 1,
    "masterKecamatanId" : 1,
    "masterDesaId" : 1,
    "masterNegaraId" : 1,
    "alamatKantor" : "Panjer",
    "waAdmin" : "0984937483900"
}

### GET ONE SUMBER DAYA PARTAI / KEANGGOTAAN
GET http://localhost:3000/api/sumber-daya-partai/sumber-daya-partai-get-one?id=clgg9oijk0017acoj2t8ort8m HTTP/1.1


###SEEDER USER ROLE
POST  http://localhost:3000/api/seeder/api-seeder-user HTTP/1.1
Content-Type: application/json

{
    "username":"amaliaz",
    "email":"amalia@gmail.com",
    "password":"123"
}




###### GET WILAYAH PROVINSI
GET http://localhost:3000/api/master/master-provinsi-get-all HTTP/1.1

###### GET WILAYAH KABKOT
GET http://localhost:3000/api/master/master-kabkot-get-by-provinsi?idProvinsi=5 HTTP/1.1

### GET WILAYAH KECAMATAN
GET http://localhost:3000/api/master/master-kecamatan-get-by-kabkot?idKabkot=2 HTTP/1.1


### GET WILAYAH DESA
GET http://localhost:3000/api/master/master-desa-get-by-kecamatan?idKecamatan=3 HTTP/1.1