export var namaHewan = [
    "Tapir",
    "Elang laut",
    "Buaya",
    "Alpaka",
    "Semut",
    "Tenggiling",
    "Kijang",
    "Kera",
    "Armadillo",
    "Keledai",
    "Babon",
    "Luak",
    "Barakuda",
    "Kelelawar",
    "Beruang",
    "Berang-berang",
    "Lebah",
    "Banteng",
    "Babi",
    "Kerbau",
    "Kupu-kupu",
    "Unta",
    "Kapibara",
    "Karibu",
    "Kasuari",
    "Kucing",
    "Ulat",
    "Ternak",
    "Chamois",
    "Cheetah",
    "Ayam",
    "Simpanse",
    "Chinchilla",
    "batuk",
    "Kerang",
    "Kobra",
    "Kecoak",
    "Ikan kod",
    "Dandang",
    "Anjing hutan",
    "Kepiting",
    "Derek",
    "Buaya",
    "Burung gagak",
    "Keriting",
    "Rusa",
    "Dinosaurus",
    "Anjing",
    "Ikan anjing",
    "Lumba-lumba",
    "Dotterel",
    "Merpati",
    "Capung",
    "Bebek",
    "Dugong",
    "Dunlin",
    "Burung rajawali",
    "Echidna",
    "Belut",
    "Eland",
    "Gajah",
    "Rusa besar",
    "Emu",
    "Elang",
    "Musang",
    "Finch",
    "Ikan",
    "Flamingo",
    "Terbang",
    "Rubah",
    "Katak",
    "Gaur",
    "Kijang",
    "Gerbil",
    "Jerapah",
    "Agas",
    "Gnu",
    "Kambing",
    "Uang emas",
    "Ikan mas",
    "Angsa",
    "Gorila",
    "Goshawk",
    "Belalang",
    "Menggerutu",
    "Guanaco",
    "Camar",
    "Hamster",
    "Kelinci",
    "Elang",
    "Landak",
    "Bangau",
    "Ikan haring",
    "Kuda nil",
    "Pikat",
    "Kuda",
    "Manusia",
    "Kolibri",
    "Dubuk",
    "Ibex",
    "Ibis",
    "Serigala",
    "Jaguar",
    "Jay",
    "Ubur ubur",
    "Kanguru",
    "Burung pekakak",
    "Koala",
    "Kookabura",
    "Kouprey",
    "Kudu",
    "Lapwing",
    "Lark",
    "Kubung",
    "Macan Tutul",
    "Singa",
    "Lama",
    "Lobster",
    "Belalang",
    "Loris",
    "Kutu",
    "Burung Lyre",
    "Burung murai",
    "Mallard",
    "Manatee",
    "Mandril",
    "Belalang",
    "Kukus",
    "Meerkat",
    "Cerpelai",
    "Tikus tanah",
    "Luwak",
    "Monyet",
    "Rusa",
    "Nyamuk",
    "Mouse",
    "Bagal",
    "Paus Bor",
    "Kadal air",
    "Bulbul",
    "Gurita",
    "Okapi",
    "Semacam tupai",
    "Oriks",
    "Burung unta",
    "Berang-berang",
    "Burung hantu",
    "Tiram",
    "Harimau kumbang",
    "Burung beo",
    "Ayam hutan",
    "Merak jantan",
    "Pelikan",
    "Pinguin",
    "Pegar",
    "Babi",
    "Merpati",
    "Kuda poni",
    "Landak",
    "Lumba-lumba",
    "Burung puyuh",
    "Quelea",
    "Quetzal",
    "Kelinci",
    "Rakun",
    "Rel",
    "Ram",
    "Tikus",
    "Gagak",
    "Rusa merah",
    "Panda Merah",
    "Rusa kutub",
    "Badak",
    "Benteng",
    "Salamander",
    "Ikan salmon",
    "Dolar Pasir",
    "Burung kedidi",
    "Sarden",
    "Kalajengking",
    "Kuda laut",
    "Segel",
    "Hiu",
    "Domba",
    "Tikus",
    "Sigung",
    "Siput",
    "Ular",
    "Burung gereja",
    "Laba-laba",
    "Sendok",
    "Cumi-cumi",
    "Tupai",
    "Burung Jalak",
    "Ikan pari",
    "Kutu busuk",
    "Bangau",
    "Angsa",
    "Angsa",
    "Tenuk",
    "Tarsius",
    "Rayap",
    "Harimau",
    "Kodok",
    "Ikan trout",
    "Turki",
    "Penyu",
    "Ular berbisa",
    "Burung bangkai",
    "Wallaby",
    "Anjing laut",
    "Tawon",
    "Musang",
    "Paus",
    "Kucing garong",
    "Serigala",
    "Wolverine",
    "Wombat",
    "Kayu",
    "Burung pelatuk",
    "Cacing",
    "Burung Gelatik",
    "Yak",
    "Zebra"
]